name: Build, scan and push artifact

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get short SHA
        id: get-sha
        run: "echo ::set-output name=short_sha::$(git rev-parse --short HEAD)"

      # - name: Get sa values
      #   id: debug
      #   run: |
      #     echo ${{ secrets.GCP_SA }}

      - name: Build docker image
        uses: docker/build-push-action@v5
        with:
          context: ./microservice
          push: false
          tags: |
            ${{ vars.CR_URL }}/microservice:${{ steps.get-sha.outputs.short_sha }}
            ${{ vars.CR_URL }}/microservice:latest
            localbuild/microservice:latest
          # # used for debugging
          # tags: |
          #   localbuild/microservice:latest

      - name: Artifact vulnerability scan
        id: imagescan
        uses: anchore/scan-action@v3
        with:
          image: "localbuild/microservice:latest"
          severity-cutoff: high
          output-format: table

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: us-central1-docker.pkg.dev
          username: __json_key_base64
          password: ${{ secrets.GCP_SA }}

      - name: Push docker image
        uses: docker/build-push-action@v5
        with:
          context: ./microservice
          push: true
          tags: |
            ${{ vars.CR_URL }}/microservice:${{ steps.get-sha.outputs.short_sha }}
            ${{ vars.CR_URL }}/microservice:latest

      - name: Update the container image url
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          IMAGE_TAG: ${{ vars.CR_URL}}/microservice:${{ steps.get-sha.outputs.short_sha }}
        run: |
          curl -L \
            -X PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "X-Github-Api-Version: 2022-11-28" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            https://api.github.com/repos/$REPO/actions/variables/CR_IMG \
            -d "{\"name\":\"CR_IMG\",\"value\":\"$IMAGE_TAG\"}"
        # run: |
        #   echo "Repository name: $REPO"
