name: CI/CD Workflow pipeline

on:
  workflow_run:
    workflows: ["Source code vulnerability scan"]
    types: ["completed"]

jobs:
  exec_artifact:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}
    uses: ./.github/workflows/build_scan_push.yaml

  deploy_staging:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}
    uses: ./.github/workflows/deploy_staging.yaml
    needs: exec_artifact

  deploy_prod:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}
    uses: ./.github/workflows/deploy_prod.yaml
    needs: deploy_staging
